<h1>Alaska Airlines</h1>

<p><b>Alaska Airlines</b> is a major American airline headquartered in SeaTac, Washington, within the Seattle metropolitan area. It is the fifth largest airline in the United States when measured by fleet size, scheduled passengers carried, and the number of destinations served. Alaska, together with its regional partners Horizon Air and SkyWest Airlines, operate a large domestic route network, primarily focused on connecting from the Pacific Northwest, West Coast, and Alaska to over one hundred destinations in the contiguous United States, Hawaii, Belize, Canada, Costa Rica, and Mexico.

    The airline operates out of five hubs, with its primary hub being at Seattle–Tacoma International Airport.[4] Alaska Airlines is a member of Oneworld alliance, the third largest airline alliance in the world.[5] As of 2020, the airline employs over 16,000 people and been ranked by J. D. Power and Associates as having the highest customer satisfaction of the traditional airlines for twelve consecutive years.[6]</p>

<h3><u>Early years (1932–1945)</u></h3>
<img src="/image/Mg.jpg">
<p><b>McGee Airways</b>, a precursor to Alaska Airlines, flew its first regular but unscheduled service between Anchorage and Bristol Bay.[7] A flight took place when there were passengers or a load of cargo or mail.[8]

    The airline struggled financially during the Great Depression. There were too many airlines in Anchorage at the time, and not enough demand to support them. The first of these mergers was in 1934, when McGee sold his namesake airline for US$50,000 to Star Air Service, an airline also located in Anchorage. This allowed McGee to enter the mining industry.[9] With a fleet of fifteen aircraft, Star Air Service was a dominant airline in Alaska. But Star continued to struggle financially because of high maintenance costs for its wood and fabric planes.[10]
    
    In 1937, McGee came back to the airline and opened a liquor store, and the airline began flying liquor to remote Alaskan communities. That year, Star Air Service purchased Alaska Interior Airlines and was incorporated as Star Air Lines.[8] Star was again sold later that year to a group of miners.[9]
    
    In 1938, federal regulation began when Congress created the Civil Aeronautics Board (CAB). The CAB awarded the airline most of the routes that it wanted in Alaska, but the coveted route between Seattle and Anchorage was awarded to Pan American Airways.[10]
    
    In 1941, Star Air Service was purchased by Raymond Marshall, a businessman from New York. In 1942, the airline purchased three other airlines in Alaska, Lavery Air Service, Mirow Air Service, and Pollack Flying Service as well as a hangar at the Anchorage airport. That year, the airline's name was changed to Alaska Star Airlines.[10] The name Alaska Airlines was adopted on May 2, 1944, having narrowly beaten a competitor who was also applying for the name.[7] In the 1940s Alaska's headquarters were in Anchorage.[11]
    
    When the United States entered World War II in December 1941, Alaska Airlines faced a shortage of pilots. During the war, the airline lacked funds and equipment, and pilots were often forced to buy fuel for their planes out of their own pockets. The company, which was frequently subjected to lawsuits, also went through many different presidents during this time. In 1943, Alaska Airlines purchased the Lockheed Model 18 Lodestar, its first multi-engine aircraft. That same year the company's stock was traded for the very first time on the American Stock Exchange.[9][10]</p>
<h3><u>Expansion after World War II (1945–1949)</u></h3>
<img src="/image/al.jpg">
<p>In 1945, <b>Alaska Airlines</b> hired its first stewardesses.[10] In 1947, jockey James Wooten became president of the airline and he began to expand the airline greatly.[10][11] Under his leadership, the company purchased many surplus military aircraft from the government that were used during World War II. The airline purchased Douglas DC-3s, Douglas DC-4s and Curtiss-Wright C-46 Commandos.[7] Alaska Airlines was the first carrier certified to operate DC-3s on skis.[9]

    Alaska Airlines' large charter business made it profitable, and the airline moved its base of operations to Paine Field, an airport north of Seattle. It kept a branch office in Anchorage, however. Despite its success, Alaska Airlines' worldwide charter business was short-lived. In 1949, the CAB tightened its regulations and placed heavy fines on the airline and shut it down completely for safety violations. The airline was prohibited from operating worldwide charter flights, and president James Wooten left the company.[9][10] Also in 1949, Alaska Air began operating five Bell 47B helicopters in order to support oil exploration on the North Slope thus becoming the first airline in Alaska to operate rotary-wing aircraft.[12]
    
    In 1949, the airline was a major participant in an effort by the newly established state of Israel to airlift Jews out of Yemen to Israel in what became known as Operation Magic Carpet. C-46 or DC-4 aircraft were used for the nearly 3,000-mile flight, made necessary to avoid overflying Arab nations. Planes flew from Eritrea to Aden, then along the Gulf of Aqaba to Tel Aviv. After unloading the refugees, crews then immediately continued to Cyprus, afraid to stay on the ground in Tel Aviv for fear of being bombed. Some 49,000 Yemenite Jews were airlifted by Alaska Airlines and other carriers without a single loss of life.[13]</p>
<h3><u>Jet age (1960s)</u></h3>
<img src="/image/fly.jpg">
<p>In 1961, competitors began introducing jets on routes Alaska Airlines flew. To counter this competition, Willis negotiated with aircraft manufacturer Convair to purchase a Convair 880 jetliner with no money down for use on routes between Alaska and the contiguous United States. The company introduced the new jet aircraft the same year. In 1966 the company received its first Boeing 727-100 jets and removed the Convair 880 from the fleet as a financing condition by Boeing concerning the purchase of the 727 jetliners. Several of Alaska's first 727s were series 100C models which could be operated either as all cargo freighters, in an all passenger configuration or as mixed passenger/freight combi aircraft. In the spring of 1967, greatly increased passenger loads required quick addition of fleet aircraft and Alaska purchased a Convair 990 jetliner formerly operated by Brazilian air carrier Varig as PP-VJE which then became Alaska Airlines N987AS. This aircraft remained in service along with an increased fleet of Boeing 727-100's which were then joined by stretched Boeing 727-200s which in turn became Alaska Airlines' signature aircraft for the next 25 years. It also became the first carrier to fly the Lockheed L-100 Hercules (L382 model), the civil version of the military C-130 cargo turboprop, which was used to transport oil drilling rigs to Alaska's North Slope and later to Ecuador.[8] Alaska also owned Lockheed Constellation propliners including two Lockheed L-1649A Starliners from 1962 to 1968, and three L-1049's which were used for Military Air Transport Service operations.[citation needed] Smaller prop and turboprop aircraft were also operated, including the Convair 240, de Havilland Canada DHC-6 Twin Otter and Super Catalina amphibian aircraft as well as two versions of the Grumman Goose amphibian aircraft, one with piston engines and the other model being a conversion to turboprop engines which the airline called the "Turbo-Goose".[14] The Catalina and Grumman amphibian seaplane aircraft joined the fleet when the airline acquired local southeast Alaska operator Alaska Coastal Airlines in 1968.</p>
<style>
        h1{
            color: rgb(62, 148, 230);
        }
    </style>